version: 2
project_name: idpbuilder

before:
  hooks:
    - go mod tidy
release:
  # Mark nightly build as prerelease based on tag
  prerelease: auto

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/cnoe-io/idpbuilder/pkg/cmd/version.idpbuilderVersion={{ .Version }}
      - -X github.com/cnoe-io/idpbuilder/pkg/cmd/version.gitCommit={{ .FullCommit }}
      - -X github.com/cnoe-io/idpbuilder/pkg/cmd/version.buildDate={{ .CommitDate }}
      - -w
      - -s
    binary: idpbuilder
    ignore:
      - goos: linux
        goarch: '386'
archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ .Os }}-{{ .Arch }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  use: github
  format: "{{.SHA}}: {{.Message}} [{{.AuthorName}}](@{{.AuthorUsername}})" 
  groups:
    - title: "✨ Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug fixes"
      regexp: '^.*?(fix|bug)(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "🔧 Others"
      order: 999
